version: '2'

services:

  vi:
    build:
      context: .
    environment:
      PROXY_HOST: "http://tor-polipo-haproxy:5566"
    volumes:
      - ./crawler/result:/app/crawler/result
    command: make run
    depends_on:
      - tor-polipo-haproxy
    links:
      - tor-polipo-haproxy

  tor-polipo-haproxy:
    image: mattes/rotating-proxy
    environment:
      tors: 5
    ports:
      - "5566:5566"
      - "4444:4444"
